MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.09.20

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,37 +4,61 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=34
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "LfXp24+HaUnRA/D68Peq9jWcUXL06SpRph4swl5ctFdw5bHfRyEyufXc7rOlgJXUXu3GC9PnkXWPqxRdpgYDJjfNDX33Tl5q1iXcYRw7QVYphKT3cyzRNvkABkbzltMDJP7zMx+0wEfzFhjm4gCia/Lbv2KEm6pzCCksspEx0tnktO9CIa5L/aOznUgFkRrKjdeSuNnEhh0IaxakNEKlQz+mOi9MsJJ7mOuUMK6H5kNy8T+qVJXepOHwRTOiB7jwB2avTS7LeXXR2luLREcnFSVN3ecYEsqSiTYi1CkaK1VgQVLXkmKB8B9J/oFlI7oH21FaI0Hz3TRJDNpQvUzQvtQAQPDJNGhm8ipTiAOlH+kEKD5QDgC+1WQ+1k8Ru/99p7aIqS6mRHdoT9xO5xUreUQokwFNTCzMwDn7reYincLn31/EsYXVcGg9rkwTSNCa4LIAF9nkgcFOYRxgSt+KNSQgvlb1piZcZcLs+HlhEHnkRLjZCmC053mzatYyvKi2FeXZTKIKn6ZeTmXH5JyT8Lj5W73sMACOeaXbuebCldzG4L/e6nZ/ZzlPHyDwxrgewGkixVkMcMAwmcN3YyFKErbWmxDr29ypfHqC895LORH2GSEdI4oY9ljiMt4VAYvriai7s6PyUWiwUDa4fDWFEP4b0CvjpNCOPhqx6AvMRWM="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
-      MINICONDA_URL="http://repo.continuum.io/miniconda"
+      echo ""
+      echo "Installing a fresh version of Miniconda."
+      MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
-      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
+      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
